name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npx cypress install

      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'main'

      - run: npx nx reset # Cache tisztítása
      
      # Affected projektek listázása
      - name: Print Affected Projects
        run: npx nx print-affected --base=main --select=projects
      
      # Részletes időzítési report
      - name: Run Affected with Report
        run: |
          echo "=== Starting Affected Analysis ==="
          npx nx affected --base=main -t lint test build e2e --verbose
          echo "=== Affected Tasks Report ==="
          npx nx report

      # Opcionális: Build idő mentése artifact-ként
      - name: Save Build Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: nx-report
          path: dist/nxdeps.json