name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npx cypress install

      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'main'

      - run: npx nx reset # Cache tisztítása

      # Új parancsok az Nx 19-hez
      - name: Show Affected Projects
        run: npx nx show projects --affected --base=main

      - name: Show Affected Graph
        run: npx nx affected --graph -t build --base=main

      # Futtatás és időmérés
      - name: Run Affected Tasks with Timing
        run: |
          echo "=== Starting Affected Analysis ==="
          time npx nx affected --base=main -t lint test build e2e --verbose

      # Build report mentése
      - name: Save Build Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nx-report
          path: dist/nxdeps.json
