name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npx cypress install

      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'main'

      # Csak az érintett projektek listázása
      - name: List Affected Projects
        run: npx nx show projects --affected --base=main

      # Futtatás időméréssel
      - name: Run and Time Affected Tasks
        run: |
          echo "=== Running Affected Tasks ==="
          time npx nx affected --base=main -t lint test build e2e --configuration=ci