name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Install Cypress
      - name: Install Cypress
        run: npx cypress install

      # Clear Nx cache
      - name: Clear Nx cache
        run: npx nx reset

      # Set Nx SHAs
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'main'

      # Lint
      - name: Run lint
        run: npx nx affected -t lint

      # Build
      - name: Run build
        run: npx nx affected -t build

      # Unit tests
      - name: Run tests
        run: npx nx affected -t test

      # E2E tests
      - name: Run e2e tests
        run: npx nx affected -t e2e

      # Opcion치lisan hozz치adhatod a Nx Cloud integr치ci칩t:
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e"
